/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: '#2039ba',
        'on-primary': '#ffffff',
        'primary-container': '#3e54d3',
        'on-primary-container': '#d8dbff',
        'primary-fixed': '#dee0ff',
        'primary-fixed-dim': '#bbc3ff',
        'on-primary-fixed': '#000f5d',
        'on-primary-fixed-variant': '#1c35b7',
        secondary: '#4648d4',
        'on-secondary': '#ffffff',
        'secondary-container': '#6063ee',
        'on-secondary-container': '#fffbff',
        'secondary-fixed': '#e1e0ff',
        'secondary-fixed-dim': '#c0c1ff',
        'on-secondary-fixed': '#07006c',
        'on-secondary-fixed-variant': '#2f2ebe',
        tertiary: '#004f72',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#006895',
        'on-tertiary-container': '#bee2ff',
        'tertiary-fixed': '#c9e6ff',
        'tertiary-fixed-dim': '#89ceff',
        'on-tertiary-fixed': '#001e2f',
        'on-tertiary-fixed-variant': '#004c6e',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        surface: '#f8f9ff',
        'surface-dim': '#cbdbf5',
        'surface-bright': '#f8f9ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#eff4ff',
        'surface-container': '#e5eeff',
        'surface-container-high': '#dce9ff',
        'surface-container-highest': '#d3e4fe',
        'surface-variant': '#d3e4fe',
        'surface-tint': '#3a50d0',
        'on-surface': '#0b1c30',
        'on-surface-variant': '#444654',
        outline: '#757685',
        'outline-variant': '#c5c5d6',
        'inverse-surface': '#213145',
        'inverse-on-surface': '#eaf1ff',
        'inverse-primary': '#bbc3ff',
        background: '#f8f9ff',
        'on-background': '#0b1c30',
      },
      fontFamily: {
        sans: ['Geist', 'system-ui', 'sans-serif'],
      },
      spacing: {
        xs: '4px',
        sm: '8px',
        base: '8px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        '2xl': '48px',
        'margin-mobile': '16px',
        'margin-desktop': '40px',
        gutter: '24px',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      fontSize: {
        'headline-xl': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '14px', letterSpacing: '0.04em', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
};
